[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip']

[phases.install]
cmds = [
    'python3 -m ensurepip --upgrade',
    'python3 -m pip install --no-cache-dir -r requirements.txt'
]

[start]
cmd = 'python3 discord_bot.py'

[variables]
PYTHONUNBUFFERED = "1" 