[phases.setup]
nixPkgs = [
    "python311",
    "python311Packages.pip",
    "python311Packages.discordpy",
    "python311Packages.openpyxl",
    "python311Packages.pandas",
    "python311Packages.python-dotenv",
    "python311Packages.setuptools",
    "python311Packages.wheel"
]

[phases.install]
cmds = [
    "python3 -m ensurepip",
    "python3 -m pip install --upgrade pip",
    "python3 -m pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "python3 discord_bot.py"

[variables]
PYTHONUNBUFFERED = "1"
PYTHONPATH = "/app:${PYTHONPATH}"
PATH = "/root/.local/bin:${PATH}" 