[phases.setup]
nixPkgs = [
    "python311",
    "python311Packages.discord.py",
    "python311Packages.openpyxl",
    "python311Packages.pandas",
    "python311Packages.python-dotenv"
]

[phases.install]
cmds = [
    "python3 -m pip install --user --no-cache-dir -r requirements.txt"
]

[start]
cmd = "python3 discord_bot.py"

[variables]
PYTHONUNBUFFERED = "1"
PYTHONPATH = "/app:${PYTHONPATH}" 